### ISSUE TITLE
extract a user ID

### ISSUE THREAD

**Issue by ConnorFoody** [me-next/menext-app#51] opened 2017-03-28 00:50 UTC
Need to get some unique identifier for that can't easily be guessed (ie not an email address, but a hashed email would be OK)

**Comment by daniel-centore** [comment] 2017-03-28 00:53
Why can't we just produce a secure random string when the user logs in?

Is this a duplicate of https://github.com/me-next/menext-backend/issues/21 ?

**Comment by ConnorFoody** [comment] 2017-03-28 15:36
Yup, it's a duplicate, good find. Lets just generate a string.

**Comment by daniel-centore** [comment] 2017-03-28 15:38
I suppose it's not exactly a duplicate, since the other one is for generating the string server-side and we can treat this as the issue for actually using in client-side.

**Comment by ConnorFoody** [comment] 2017-03-28 15:44
Yeah, then we should get rid of the other one.

**Closed as completed** 2017-04-02 16:58 UTC
Labels: enhancement
